version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: lockmylook-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: lockmylook
      POSTGRES_USER: lockmylook
      POSTGRES_PASSWORD: lockmylook

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: