from pathlib import Path
from uuid import uuid4

from app.virtual_try_on.cache import build_vto_cache_key


def test_vto_cache_key_is_deterministic_and_provider_agnostic(tmp_path: Path):
    person = tmp_path / "person.png"
    garment = tmp_path / "garment.jpg"
    person.write_bytes(b"person-image")
    garment.write_bytes(b"garment-image")

    profile_id = uuid4()
    item_id = uuid4()

    base = dict(
        profile_id=profile_id,
        person_path=person,
        garment_paths=[garment],
        item_ids=[item_id],
    )

    first = build_vto_cache_key(**base)
    second = build_vto_cache_key(**base)

    assert first == second
    assert len(first) == 64


def test_vto_cache_key_is_identical_for_different_models(tmp_path: Path):
    person = tmp_path / "person.png"
    garment = tmp_path / "garment.jpg"
    person.write_bytes(b"person-image")
    garment.write_bytes(b"garment-image")

    base = dict(
        profile_id=uuid4(),
        person_path=person,
        garment_paths=[garment],
        item_ids=[uuid4()],
    )

    # Provider/model is deliberately absent from the cache key. A result
    # generated by one provider is reusable by every other provider.
    assert build_vto_cache_key(**base) == build_vto_cache_key(**base)


def test_vto_cache_key_changes_when_garment_changes(tmp_path: Path):
    person = tmp_path / "person.png"
    garment = tmp_path / "garment.jpg"
    person.write_bytes(b"person-image")
    garment.write_bytes(b"garment-image")

    kwargs = dict(
        profile_id=uuid4(),
        person_path=person,
        garment_paths=[garment],
        item_ids=[uuid4()],
    )

    original = build_vto_cache_key(**kwargs)
    garment.write_bytes(b"different-garment-image")
    changed = build_vto_cache_key(**kwargs)

    assert original != changed


def test_vto_cache_key_changes_when_person_changes(tmp_path: Path):
    person = tmp_path / "person.png"
    garment = tmp_path / "garment.jpg"
    person.write_bytes(b"person-image")
    garment.write_bytes(b"garment-image")

    kwargs = dict(
        profile_id=uuid4(),
        person_path=person,
        garment_paths=[garment],
        item_ids=[uuid4()],
    )

    original = build_vto_cache_key(**kwargs)
    person.write_bytes(b"different-person-image")
    changed = build_vto_cache_key(**kwargs)

    assert original != changed


def test_vto_cache_key_preserves_garment_order(tmp_path: Path):
    person = tmp_path / "person.png"
    garment_one = tmp_path / "garment1.jpg"
    garment_two = tmp_path / "garment2.jpg"
    person.write_bytes(b"person-image")
    garment_one.write_bytes(b"first")
    garment_two.write_bytes(b"second")

    profile_id = uuid4()
    first_item = uuid4()
    second_item = uuid4()

    ordered = build_vto_cache_key(
        profile_id=profile_id,
        person_path=person,
        garment_paths=[garment_one, garment_two],
        item_ids=[first_item, second_item],
    )
    reversed_order = build_vto_cache_key(
        profile_id=profile_id,
        person_path=person,
        garment_paths=[garment_two, garment_one],
        item_ids=[second_item, first_item],
    )

    assert ordered != reversed_order
